prefix ssn: <http://purl.oclc.org/NET/ssnx/ssn#>
prefix time: <http://www.w3.org/2006/time#>
prefix dul: <http://www.loa-cnr.it/ontologies/DUL.owl#>
prefix xsd: <http://www.w3.org/2001/XMLSchema#>
prefix qudt: <http://qudt.org/schema/qudt#>
prefix ex: <http://example.org#>

select ?time ?value ?unit
where {
[
    ssn:observedBy ex:thermometer ;
    ssn:observedProperty ex:temperature ;
    ssn:featureOfInterest ex:air ;
    ssn:observationResultTime [ time:inXSDDateTime ?time ] ;
    ssn:observationResult [ ssn:hasValue [ qudt:numericValue ?value; qudt:unit ?unit ] ] 
] 
    filter (?time >= "2015-06-01T12:00:00.000+03:00"^^xsd:dateTime 
    	&& ?time < "2015-07-01T12:00:00.000+03:00"^^xsd:dateTime)
}
order by asc(?time)